### ISSUE TITLE
[ARM] SubscriptionRequired field is ignored when deploying

### ISSUE THREAD

**Issue by MichalKosowski** [Azure/azure-api-management-devops-resource-kit#194]
Hi,

I have following template setting in yaml file:

`apis:`
`  - name: Api1`
`    serviceUrl: https://url.azurewebsites.net/api/`
`    openApiSpec: \swagger.json`
`    policy: \policy.api.xml`
`    suffix: client`
`    subscriptionRequired: false`
`    operations: `
`      # operations settings`
`    authenticationSettings: `
`      subscriptionKeyRequired: false``

Where **"subscriptionRequired": false,**, and same with authentication. Api is not added to any product. Generated template is:

` "resources": [`
`    {`
`      "properties": {`
`        "authenticationSettings": {`
`          "subscriptionKeyRequired": false`
`        },`
`        "isCurrent": false,`
`        "subscriptionRequired": false,`
`        "displayName": "",`
`        "path": "",`
`        "protocols": [`
`          "https"`
`        ],`
`        "value": "swagger content"`
`        "format": "swagger-json"`
`      },`
`      "name": "name",`
`      "type": "Microsoft.ApiManagement/service/apis",`
`      "apiVersion": "2019-01-01",`
`      "dependsOn": []`
`    },`

So the subscription settings are set properly. However, after deploying to Azure, checkbox is checked...

![obraz](https://user-images.githubusercontent.com/48284314/58943888-fe171500-8780-11e9-9fda-29ccb5668a38.png)

Am I doing something wrong or there is an issue with that?

**Comment by miaojiang** [comment]
Fixed.

**Comment by gd201712** [comment]
Hi @miaojiang, I am still seeing this issue when I depoly an API via ARM with the subscriptionKeyRequired parameter set to false. Has the fix being made generally available? I am deploying the the "West Europe" region. Thanks, Gary
